<<<<<<< HEAD
name: Run UI and API Tests

on:
  push:
    branches: [ main ]
=======
name: Run All Tests

on:
>>>>>>> 27c271d (push Feedback)
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD

=======
>>>>>>> 27c271d (push Feedback)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

<<<<<<< HEAD
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run API Tests
        run: ./gradlew testApi

      - name: Run Web UI Tests
        run: ./gradlew testWeb

      - name: Upload Cucumber HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: build/reports/
=======
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle
        run: chmod +x gradlew

      - name: Run API Tests
        run: ./gradlew runApiTests

      - name: Run Web Tests
        run: ./gradlew runWebTests
>>>>>>> 27c271d (push Feedback)
